# Generated by Django 5.1.6 on 2025-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField()),
                ('status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], max_length=50)),
            ],
        ),
    ]
