# Generated by Django 5.1.6 on 2025-02-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
