# Generated by Django 5.1.6 on 2025-02-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0004_usergroup_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
