# Generated by Django 5.1.6 on 2025-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_tablelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=100, unique=True)),
                ('menu_item_desc', models.CharField(max_length=255)),
                ('item_seq', models.PositiveIntegerField()),
                ('module_name', models.CharField(max_length=100)),
                ('main_menu_action_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], max_length=10)),
            ],
        ),
    ]
