# Generated by Django 5.1.6 on 2025-02-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_mainmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuId', models.CharField(max_length=100)),
                ('menuItemDesc', models.CharField(max_length=255)),
                ('itemSeq', models.IntegerField()),
                ('moduleName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('main_menu_action_name', models.CharField(max_length=255)),
                ('main_menu_icon_name', models.CharField(max_length=255)),
            ],
        ),
    ]
